### ISSUE TITLE
org.apache.commons.lang3.jar missing from Mendix 8 release

### ISSUE THREAD

**Issue by robertprice** [mendix/CommunityCommons_ObjectHandling#4]
The required jar file org.apache.commons.lang3.jar is missing from the packaged version 3 release used on Mendix 8 projects. This causes compilation errors when using this module in Mendix 8. Can it be added to the release please? I can see it is in the repository.

**Comment by RoelandSalij** [comment]
Thanks for the heads up! Fixed in v3.0.1
